spring.application.name=shipping-service

server.servlet.context-path=/api/v1/shipping
server.port=9015

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/shipmentdb
spring.datasource.username=akshityadav
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

debug=true

