spring.application.name=order-service
spring.config.import=configserver:http://localhost:8888

#server.servlet.context-path=/api/v1
#server.port=9012
#
##DB configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/orderServiceDB
#spring.datasource.username=akshityadav
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
#
##spring.jpa.defer-datasource-initialization=true
##spring.sql.init.mode=always
##spring.sql.init.data-locations=classpath:data.sql
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#debug=true