spring.application.name=inventory-service

server.servlet.context-path=/api/v1
server.port=9011

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/inventoryDB
spring.datasource.username=akshityadav
spring.datasource.password=root1234

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true

debug=true

# eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka